volumes:
  db_data:
    name: 'db_data' 

services:
  web:
    build: .
    environment:
      - DB_HOST=db
      - DB_NAME=api
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api
    ports:
      - '5432:5432'
    volumes: 
      - db_data:/var/lib/postgresql/data
    